# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'IceClassExplorer' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
        build_config.build_settings['GCC_WARN_ABOUT_RETURN_TYPE'] = 'YES'
        build_config.build_settings['CLANG_WARN_OBJC_ROOT_CLASS'] = 'YES'
        build_config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'

        if ['fmt', 'Yoga'].include?(target.name)
          build_config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        end

        ['OTHER_CFLAGS', 'OTHER_CPLUSPLUSFLAGS'].each do |key|
          value = build_config.build_settings[key]
          value = '$(inherited)' unless value

          flags = value.is_a?(Array) ? value : value.split(' ')
          filtered_flags = flags.reject { |flag| flag == '-Werror' || flag.start_with?('-Werror=') }
          filtered_flags << '-Wno-error=return-type'
          filtered_flags << '-Wno-error=non-modular-include-in-framework-module'
          filtered_flags << '-Wno-error=deprecated-objc-isa-usage'
          filtered_flags << '-Wno-error=objc-root-class'
          filtered_flags << '-w' if ['fmt', 'Yoga'].include?(target.name)
          filtered_flags = filtered_flags.uniq
          build_config.build_settings[key] = value.is_a?(Array) ? filtered_flags : filtered_flags.join(' ')
        end
      end

      source_phase = target.respond_to?(:source_build_phase) ? target.source_build_phase : nil
      next unless source_phase

      source_phase.files.each do |file|
        next unless file.settings && file.settings['COMPILER_FLAGS']

        flags = file.settings['COMPILER_FLAGS'].split
        filtered_flags = flags.reject { |flag| flag == '-Werror' || flag.start_with?('-Werror=') }
        filtered_flags << '-w' if ['fmt', 'Yoga'].include?(target.name)
        file.settings['COMPILER_FLAGS'] = filtered_flags.uniq.join(' ')
      end
    end
  end
end
